export enum EFFECTS {
  STANDARD = 'STANDARD',
  PIXELATE = 'PIXELATE',
  ASCII = 'ASCII',
  // SLITSCAN = 'SLITSCAN',
  GRID = 'GRID',
}

export const effectsList = [
  EFFECTS.STANDARD,
  EFFECTS.PIXELATE,
  EFFECTS.ASCII,
  // EFFECTS.SLITSCAN,
  EFFECTS.GRID,
];
