export enum EFFECTS {
  STANDARD = 'STANDARD',
  PIXELATE = 'PIXELATE',
  ASCII = 'ASCII',
  GRID = 'GRID',
  SLITSCAN = 'SLITSCAN',
}

export const effectsList = [
  EFFECTS.STANDARD,
  EFFECTS.PIXELATE,
  EFFECTS.ASCII,
  EFFECTS.GRID,
  EFFECTS.SLITSCAN,
];
